//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickQR.Resx {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickQR.Resx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Barcode content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Result_About_Content_Title {
            get {
                return ResourceManager.GetString("Result.About.Content.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Result_About_Info_Format_Format {
            get {
                return ResourceManager.GetString("Result.About.Info.Format.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information on barcode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Result_About_Info_Title {
            get {
                return ResourceManager.GetString("Result.About.Info.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About barcode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Result_About_Title {
            get {
                return ResourceManager.GetString("Result.About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Result_Action_Title {
            get {
                return ResourceManager.GetString("Result.Action.Title", resourceCulture);
            }
        }
    }
}
